spring:
  application:
    name: SpringCloudStream
  cloud:
    stream:
      bindings:
        OutputChannelRabbit:
          destination: rabbit-channel
          binder: rabbit
        InputChannelRabbit:
          destination: rabbit-channel
          binder: rabbit
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/students-api-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create


spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
  web:
    exposure:
      include: '*'
  health:
    enabled: true


#management.endpoints.web.base-path=/
#management.endpoints.web.path-mapping.health=healthCheck


info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java.version: @java.version@


