global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluate rules every 5 secs
scrape_configs:
  - job_name: 'SpringBoot-application-NAB-Cloud'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093