global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluate rules every 5 secs

rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.9.1:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080'] #host and port

#    basic_auth:
#      username: "admin"
#      password: "pass"

#install prometheus
#docker pull prom/prometheus
#
#docker run -d --name=prometheus -p 9090:9090 -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml
#
#grafana
#docker run -d --name=grafana -p 3000:3000 grafana/grafana

#AlertManager:
#docker run -d --name=alertmanager -p 9093:9093 -v ./alertmanager.yml:/etc/alertmanager/alertmanager.yml prom/alertmanager